### ISSUE TITLE
Add and allow data import for NRCS/SNOTEL sites on the Data Import tab

### ISSUE THREAD

**Issue by tjrocha** [usbr/HydrometTools#11]
PN requirement is to also allow users to check the data quality of SNOTEL SWE data in Hydromet by cross-referencing published NRCS data.

**Comment by tjrocha** [comment]
Research results:
- Data loaders rely on snotel_site_list2.csv in cfg folder which maps CBTTs to NRCS Site-IDs
- NrcsSeries() code in Reclamation.TimeSeries needs NRCS Site-ID and Hydromet parameter-name to fetch TS-data

Solution Path:
- Check if sites in snotel_site_list2.csv are current with NRCS inventory
- Check if there are new NRCS Site-IDs that we would want to add to Hydromet
- Move away from using the csv file and put the NRCS metadata as into either the site_properties, site_catalog, or series_catalog.connectionstring Hydromet tables
- Clean up the entries in the Hydromet catalogs

**Comment by tjrocha** [comment]
@ktarbet - Was there a reason for running the data loaders and structuring the code to rely on the csv? Thanks!

**Comment by ktarbet** [comment]
@tjrocha  -- The original version of Hydromet tools was designed to work with VMS, so the csv files were handy.   Great Idea to use something like site_properties.  
![image](https://user-images.githubusercontent.com/4818531/69906444-31291280-1378-11ea-9bf0-706d385000ac.png)

**Comment by jdalling** [comment]
Pyforecast has a hard time pulling first of the month manual snow course data because of the collection date in the NRCS database. To address this, I think Jordan and Kevin programmed PyCast to interpolate the first of month data from the collection date. Just a thought, but it could potentially be beneficial to assign snow course data to the first of the month in hydromet and have PyCast pull it from there.

**Comment by tjrocha** [comment]
@jdalling - We made a tweak to PyForecast so it looks for _nearest neighbor_ snow-course data on this [commit](https://github.com/usbr/PyForecast/commit/39bc22b2c693d043d297874685358ef6a307380c). This will _snap_ snow course readings to the 1st or 15th provided that the measurement was made plus-or-minus 5 days of the 1st or 15th.

**Comment by jdalling** [comment]
I think it still struggles with it because plus/minus 5 days is exceeded so often.
