### ISSUE TITLE
GP Advanced Tab Updates

### ISSUE THREAD

**Issue by tjrocha** [usbr/HydrometTools#6]
Requested and coded by @kevinfol

Requests for additions to the HydroMet Tools application from some of our operators. 
1. An additional module to be added to the Advanced Tab to allow us to compute daily Ratings. Right now, the Advanced tab only allows us to compute ratings for instant data, but we'd like the ability to compute ratings from daily gage heights and forebay elevations. 

2. A module on the advanced tab that lets our operators run the "FIXINFLO" procedure directly from HydrometTools. This is a procedure that calculates the inflow for some of our more complicated reservoirs, and it is not run by the archiver.

**Comment by kevinfol** [comment]
Fixed by ea675b8
